dist: trusty
language: python
sudo: false

env:
    global:
        # Undocumented feature of nose-show-skipped.
        NOSE_SHOW_SKIPPED: 1

matrix:
    include:
        - python: 2.7.13
          env: {TOX_ENV: py27-cov, COVERAGE: 1}
        - python: 2.7.13
          env: {TOX_ENV: py27-test}
        - python: 3.4
          env: {TOX_ENV: py34-test}
        - python: 3.5
          env: {TOX_ENV: py35-test}
        - python: 3.6
          env: {TOX_ENV: py36-test}
        - python: 3.7
          env: {TOX_ENV: py37-test}
          dist: xenial
        - python: 3.8-dev
          env: {TOX_ENV: py38-test}
          dist: xenial
        - python: pypy
          env: {TOX_ENV: pypy-test}
        - python: 2.7
          env: {TOX_ENV: py27-flake8}
        - python: 3.5
          env: {TOX_ENV: py35-flake8}

# Non-Python dependencies.
addons:
    apt:
        packages:
            - bash-completion

# To install dependencies, tell tox to do everything but actually running the
# test.
install:
    - travis_retry pip install 'tox<=3.8.1'
    - travis_retry tox -e $TOX_ENV --notest

script:
    - tox -e $TOX_ENV

# Report coverage to codecov.io.
before_install:
    - "[ ! -z $COVERAGE ] && travis_retry pip install codecov || true"
after_success:
    - "[ ! -z $COVERAGE ] && codecov || true"

cache:
    pip: true
