version: "{build}"
build: off
deploy: off
skip_commits:
    # add [appveyor skip] as an alias for [skip appveyor] (like [ci skip])
    message: /\[appveyor skip\]/

environment:
    # Undocumented feature of nose-show-skipped.
    NOSE_SHOW_SKIPPED: 1

    matrix:
        - PYTHON: C:\Python27
          TOX_ENV: py27-test
        - PYTHON: C:\Python34
          TOX_ENV: py35-test
        - PYTHON: C:\Python35
          TOX_ENV: py36-test

# Install Tox for running tests.
install:
    - '%PYTHON%/Scripts/pip.exe install "tox<=3.8.1"'
    - "%PYTHON%/Scripts/tox.exe -e %TOX_ENV% --notest"

test_script:
    - "%PYTHON%/Scripts/tox.exe -e %TOX_ENV%"
